### ISSUE TITLE
Running uphold

### ISSUE THREAD

**Issue by tuxx** [forward3d/uphold#1]
Hi!

Was trying to get uphold to work, but i got the error message:

> Unable to find image 'uphold-ui:latest' locally

This was because i hadn't built the uphold-ui docker container yet. After some fiddling around i found out i had to run the `build_and_inspect_ui` script to get the docker container locally.

After this running the below command worked fine.

> docker run \
>   --rm \
>   -p 8079:8079 \
>   -v /var/run/docker.sock:/var/run/docker.sock \
>   -v /etc/uphold:/etc/uphold \
>   -v /var/log/uphold:/var/log/uphold \
>   uphold-ui:latest

Might be a good idea to add this to the documentation? Took me some time to figure it out, might save some other people the time :)

Best regards.

**Comment by lloydpick** [comment]
Ah, looks like I'm referencing the wrong container, that should be `forward3d/uphold-ui:latest` oops, I'll fix that.

Cheers!
